name: GS-raytracing
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit
  - plyfile
  - python
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
